apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xeqldume8-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f9f4a20836.vq5n.p3.openshiftapps.com/rhtap/rhtap-qe-python:04ff45bf1f8b59a093bf51fedd375d86647d8e77@sha256:d095dc86999fb78c307c7d0793e3518f77b8734a742b1a0af8b0d923dd2fec4f
          name: container-image
